### ISSUE TITLE
How to allow drag reordering of list items when centre view is a list

### ISSUE THREAD

**Issue by 3ur3ka** [Vidhyadharan24/SideMenu#1]
Thanks for a great library!

I'm trying to use a list view as the centre view, but I can't get the drag gesture to work as it seems to be hijacked by the swipe out menu logic - is there any way to get the (vertical) drag gesture to work? Perhaps something with simultaneousGesture() may work? I was really hoping you can help, as I really need the reordering functionality of the list view! Many Thanks

**Comment by 3ur3ka** [comment]
I figured out a way to disable the side menu swipe out gestures when in edit mode, and everything works now.

**Comment by Vidhyadharan24** [comment]
Great, I was looking at the sequenced and exclusively methods to resolve the issue, but both of them required an instance of the other gesture.

If you can add your solution in code here, it will help others facing the same issue.

**Comment by 3ur3ka** [comment]
I should point out that I had to modify the source to enable this feature.
So I added a var to SideMenu.swift

`@Binding private var isDisableSideMenus: Bool`

I then updated the initialisers to pass the var through as follows:

    public init<Menu: View>(leftMenu: Menu, showLeftMenu: Binding<Bool>,
                                centerView: Binding<AnyView?>, config: SideMenuConfig = 
    SideMenuConfig(), isDisableSideMenus: Binding<Bool>) {
        self._showLeftMenu = showLeftMenu
        self._showRightMenu = .constant(false)
        self._centerView = centerView
        self._isDisableSideMenus = isDisableSideMenus
        ...


And similarly for the other `init` methods.

(Where the SideMenu gets initialised in your code, you'll need a state var to pass in for the `isDisableSideMenus` var)

Then add the following to the drag gesture in the SideMenu view

    .gesture(self.isDisableSideMenus ? nil : self.panelDragGesture(geometry.size.width))

By passing the variable through to the views you should have a variable available so that you can disable the swipe out menus when needed, for example to edit a list view.

e.g. just call `isDisableSideMenus.toggle()` when you want to disable/re-enable the swipe gestures.

Hope that helps, I'm new to SwiftUI so if you think there's a better way please let me know.

**Comment by Vidhyadharan24** [comment]
I'm looking at SwiftUI's environment value "editMode" to resolve the issue, will keep you posted on the same here.

**Comment by Vidhyadharan24** [comment]
@3ur3ka I have updated the project to use environment variables instead of states and bindings for cleaner implementation. I've also added an environment variable to enable/disable the panel gesture of SideMenu. Hope this helps you out.

**Comment by 3ur3ka** [comment]
That's brilliant, thanks!
