### ISSUE TITLE
Tap outside of the panels to dismiss?

### ISSUE THREAD

**Issue by EnesKaraosman** [Vidhyadharan24/SideMenu#3]
Not sure if this functionality is already exist, I can also toggle `environment` programmatically, but I do not want to add code to each `CenterView` to dismiss panels. Is there an easier way to handle this?

By the way, when I investigated code, seems `MenuBackgroundView` should do this job but I could not get it work, can you help me to figure out.

**Comment by Vidhyadharan24** [comment]
You are right the MenuBackgroundView is responsible for hiding the panels, let me have a look at during this weekend.

**Comment by Vidhyadharan24** [comment]
Setting the opacity of `MenuBackgroundView` seems to have prevented hit test to the `MenuBackgroundView`'s children, Passing the opacity value as an argument and setting it to the rectangle directly fixes the issue.
