### ISSUE TITLE
Updating to main branch-- got additional area at top of screen

### ISSUE THREAD

**Issue by crspybits** [Vidhyadharan24/SideMenu#4]
Hi-- Thanks for this package! I've been using this for a few months on an app I'm developing. I had been seeing this view:
![IMG_4970](https://user-images.githubusercontent.com/5758762/103326117-1f4af080-4a0c-11eb-9815-2647d256d0a6.PNG)

But now, I'm seeing the following if I use the current repo main branch (the red is just to emphasize the unexpected part of the view):
![IMG_4969](https://user-images.githubusercontent.com/5758762/103326072-f75b8d00-4a0b-11eb-84c5-b48351993711.PNG)

Thoughts?

**Comment by Vidhyadharan24** [comment]
Let me check why this is happening later this week and will update it here.

**Comment by crspybits** [comment]
Thanks! Let me know if I can help/run tests.

**Comment by Vidhyadharan24** [comment]
I made some changes a while back to automaticaly embed the center view in a NavigationStack, what you are seeing is a result of that i.e your navigation stack embeded within the navigation stack provided by SideMenu.

The solution to your issue would be to unembed you center panel view from the NavigationView and passing as is to the SideMenu library.

Currently the app does not support adding custom images to the left and right sidebar buttons, if you require this feature post it here i will add support to it via SideMenuConfig values.

**Comment by crspybits** [comment]
Thanks!! I removed the `NavigationView` from my code, and it's working now. I would like a custom menu button, yes. I'll open that as a separate issue. That would be great if you could add that.
